management:
  endpoint:
    health:
      access: unrestricted
      show-details: always
    loggers:
      access: unrestricted
    bindings:
      access: unrestricted
    channels:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - bindings
          - channels
          - loggers

  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true


spring:
  application:
    name: spring-boot-cloud-stream-kafka-401
  cloud:
    stream:
      bindings:
        produceMessage-out-0:
          destination: first-topic
        consumeMessage-in-0:
          destination: first-topic
      kafka:
        binder:
          brokers: localhost:19092
          enableObservation: true
    function:
      definition: produceMessage;consumeMessage
